### ISSUE TITLE
在第一次导入项目时是成功的,但在第二次及之后打开项目时会一直显示加载中

### ISSUE THREAD

**Issue by sxx97** [dragonation/wechat-devtools#1]

**Comment by sxx97** [comment]
加载中不影响点击编译,切换编译就可以加载成功了,但是加载出来的工具调试器部分为空白如下:  
![image](https://user-images.githubusercontent.com/40782717/77890839-a9f69780-72a2-11ea-81f5-95191b94a207.png)

**Comment by dragonation** [comment]
能报告一下具体的linux版本、wine版本和开发者工具版本吗？我本地并没有复现这个问题，所以需要更多的信息来确认具体问题的根源，谢谢！

**Comment by dragonation** [comment]
个人估计是你构筑时失败了，可以考虑下载发布版本，或者用最新版重新构筑。刚修复了几个bug

**Comment by sxx97** [comment]
> 个人估计是你构筑时失败了，可以考虑下载发布版本，或者用最新版重新构筑。刚修复了几个bug

我选择了最新发布的版本运行后没有调试界面
linux发行版:  deepin 15.11  
linux内核:4.15.0-30
wine:  5.0
开发者工具:  1.02.2004020

**Comment by dragonation** [comment]
> > 个人估计是你构筑时失败了，可以考虑下载发布版本，或者用最新版重新构筑。刚修复了几个bug
> 
> 我选择了最新发布的版本运行后没有调试界面
> linux发行版: deepin 15.11
> linux内核:4.15.0-30
> wine: 5.0
> 开发者工具: 1.02.2004020

好的，晚上我具体看一下情况。另外，确认一下wine-binfmt有安装吗？
目前我这边开发环境是archlinux，kernel 5.6.2, wine 5.5。估计跟内核关系不大，我查一下有什么依赖需要的

**Comment by dragonation** [comment]
在其他的类似repo里看到一个相关类似的issue
https://github.com/cytle/wechat_web_devtools/issues/292
似乎deepin的wine有部分特化，不确定是否会造成兼容性的问题。

**Comment by dragonation** [comment]
我看到了截图，估计还是npm的native模块格式和版本不对，想确认一下node版本是多少

**Comment by sxx97** [comment]
> 我看到了截图，估计还是npm的native模块格式和版本不对，想确认一下node版本是多少

node版本: 13.5.0
我昨天也把wine升到了5.5至于deep-wine会不会对这个产生影响我也不清楚(ps:刚玩linux的菜鸡)
麻烦了大佬

**Comment by dragonation** [comment]
我估计是node版本和开发者工具需要的版本（12.6.0）不一致，我在新发布的Release中增加了PATH设定，但不知道是否有效（默认开发者工具应该不会受到系统node的影响，但不保证），你可以尝试一下。

https://github.com/dragonation/wechat-devtools/releases/tag/v1.02.2004020-2004101

**Comment by sxx97** [comment]
> 我估计是node版本和开发者工具需要的版本（12.6.0）不一致，我在新发布的Release中增加了PATH设定，但不知道是否有效（默认开发者工具应该不会受到系统node的影响，但不保证），你可以尝试一下。
> 
> https://github.com/dragonation/wechat-devtools/releases/tag/v1.02.2004020-2004101

我大概知道了原因可能是deepin中的glibc版本太旧,现在换了manjaro已经正常运行了

**Comment by QQCif** [comment]
Ubuntu 16.04 一样的问题。第一次进去没有编辑器和控制台，关掉再进就无限转圈了。下的是release里面的1.03.2006090

**Comment by sxx97** [comment]
> Ubuntu 16.04 一样的问题。第一次进去没有编辑器和控制台，关掉再进就无限转圈了。下的是release里面的1.03.2006090

debain系大概率都会这样
