### ISSUE TITLE
如何修改版本号

### ISSUE THREAD

**Issue by disburden** [dragonation/wechat-devtools#16]
deepin v20，通过解压发布的最新release版本安装的，遇到了代码编辑区空白的问题，我看到你的说明文档里说到

检查一下`conf/node.json`和`conf/nwjs.json`里面定义的版本是否与最新微信官方开发者工具的一致。如果有修改版本号的情况，则在更新完这两个JSON文件后。。。

我这个两个版本号长这样
node.json
{
    "version": "12.6.0",
    "url": "https://npm.taobao.org/mirrors/node/v${version}/node-v${version}-linux-x64.tar.gz"
}
newjs.json
{
    "version": "0.39.3",
    "url": "https://npm.taobao.org/mirrors/nwjs/v${version}/nwjs-sdk-v${version}-linux-x64.tar.gz"
}

我不知道怎么跟官方的开发工具进行比对,要怎么修改？

第一次尝试迁移到linux，很多不懂，抱歉！

**Comment by disburden** [comment]
晕，原来用兼容版本就没这个问题了
我自己关了

**Comment by dragonation** [comment]
没关系，一般我发布出来的版本都会提前查看一下和官方的版本是否对应的上。兼容版本也是看到很多朋友在深度系统上有问题，所以才特意重新生成的。不过身边也没有深度的系统，所以只能说在理论上应该可以运行，我自己只是在Docker上面测试了一下。你这边给我的情况也让我放心了下来，至少深度系统上现在已经可以使用了。毕竟国产系统，也要支持一下的啦。解决了问题就是最好的。查看版本的话，一般是跑到windows下面，运行开发者工具，里面打开调试界面以后，在console里面运行一次process.versions就可以知道了

**Comment by disburden** [comment]
辛苦辛苦！
之前用cytle的那个版本，就是遇到这个问题一直解决不了。让我一度想放弃迁移到linux的想法。
幸好有你们这样负重前行的人。让我们这些小白有乘凉的地方。感谢！

**Comment by dragonation** [comment]
没事，cytle好像最近的方向有点变化，所以项目的维护工作暂时停了下来。不过他的repo那边我也关注着，如果有issue的话，我也会那边回复帮忙解决。不过因为repo也没有在我手上，而且两边的思路有一定的区别，所以我自己是重新开了一个项目，用自己的思路来解决问题。反正问题解决了就好
