### ISSUE TITLE
模拟器无法选择版本

### ISSUE THREAD

**Issue by cliod** [dragonation/wechat-devtools#18]
系统Ubuntu20, 下载的是releases的最新版,
打开后模拟器默认是iphone5, 无法选择其他版本. 点击
![image](https://user-images.githubusercontent.com/33226980/93039709-c896f200-f67a-11ea-930d-dca2712d8209.png)
无反应.

**Comment by youleji** [comment]
最新的没试过，我用的是1.03.2006090

**Comment by cliod** [comment]
我将微信开发工具最新稳定版版1.03.2008270重新下载解压替换package.nw后可以选择模拟器, 但是编译器和调试器就没有了, 空白了

**Comment by dragonation** [comment]
问题已修复，新版本的菜单定义出了点幺蛾子

**Comment by dragonation** [comment]
刚发布了新版本，可以尝试下

**Comment by echoesink** [comment]
可以了,版本1.03.2009140
