### ISSUE TITLE
选中文本自动复制到了剪切板

### ISSUE THREAD

**Issue by looyeagee** [dragonation/wechat-devtools#2]
为啥我选择任何文本都会复制到剪切板呢？

**Comment by dragonation** [comment]
测试了一下，的确有这个问题，晚上我看一下具体是什么情况，因为平时只用开发者工具来调试，不开编辑器的，所以一直没有注意，如果有发现如何解决，后续会更新

**Comment by dragonation** [comment]
```
// Controls whether the Linux primary clipboard should be supported.
"editor.selectionClipboard": true
```

我看了一下，新版开发者工具使用了vscode的编辑器，里面默认有一个选项是在linux下自动复制选中内容的配置，你可以考虑一下禁用掉就可以了

**Comment by dragonation** [comment]
测试了一下，配置完了以后就对了
也另外写了一个工具来解决这个问题，可以通过执行`tools`目录下的`fix-selection-copy`命令来自动完成这个配置更改

**Comment by looyeagee** [comment]
感谢！
