### ISSUE TITLE
setup的时候卡在Extracting不动

### ISSUE THREAD

**Issue by likebj** [dragonation/wechat-devtools#26]
执行：lik@x230:~/program/wechat-devtools$ ./tools/setup-wechat-devtools
卡在Extracting不动：
[INFO] Extracting /home/lik/program/wechat-devtools/cache/wechat_devtools_1.03.2010240_x64.exe (wechat-devtools/tools/update-wechat-devtools:110)
可能是那的问题？

**Comment by likebj** [comment]
系统Ubuntu20.04

**Comment by likebj** [comment]
直接下载压缩包运行就行，就不用执行setup了。

**Comment by jingmian** [comment]
请问怎么直接运行？我也卡在
```sh
11-12 22:12:41.466   [INFO] Extracting /home/jingmian/wechat-devtools/cache/wechat_devtools_1.03.2010240_x64.exe 
```

**Comment by whosa** [comment]
我也碰到了这个问题，尝试按照脚本中的命令解压，发现7z会有提示询问文件已经存在，虽然我的目录都是空。所以应该是腾讯新版打包的问题。

解决方案：
在tools/update-wechat-devtools中修改第118行，在7z的解压命令后添加一个参数“-y”就行了。大概类似于下面
`@.task.execute("7z", ["x", localPath, `-o${extractPath}`, "-y", packageDir], extractPath, (error) => {`
