### ISSUE TITLE
大佬能否把releases放一下gitee，github太慢了，另外报一个编译错误

### ISSUE THREAD

**Issue by bossbaba** [dragonation/wechat-devtools#3]
编译报/username/.config/wechat_devtools/.../setting.json没有

**Comment by bossbaba** [comment]
然后依然能够打开，但是打开之后编辑器就不会出现，第二次打开的时候一直loading

**Comment by yuana1** [comment]
@bossbaba 今天我也编译安装了，  跟您的问题一模一样。
环境是ubuntu19.10  64位。
@dragonation  能否将编译包放gitee或者 网盘呢？

**Comment by dragonation** [comment]
这个bug，我已经检查过了，原因应该是第一次构筑的时候，微信的配置文件还不存在，导致刷字体的代码出错了，然后导致了后面重新编译npm native模块失败。已经提交了commit，应该会解决。

gitee，我去试看看

**Comment by dragonation** [comment]
gitee放release失败了，发布包平均文件大小要200M，但是gitee只允许100M最大，而且总体积不能超过1G……

**Comment by bossbaba** [comment]
谢谢大佬了，放不了就算啦，多花点时间来下，或者我去搞个FQ工具

**Comment by dragonation** [comment]
我上传度盘吧

**Comment by dragonation** [comment]
发布的信息里面已经加上了度盘的链接，大家应该下载起来没有那么麻烦了
