### ISSUE TITLE
劳请大佬抽空更新,十分感谢.

### ISSUE THREAD

**Issue by hanzicn** [dragonation/wechat-devtools#45]

**Comment by friddle** [comment]
https://github.com/friddle/wechat-devtools/releases/tag/2021_06_29
试验一下这个能不能用

**Comment by hanzicn** [comment]
> https://github.com/friddle/wechat-devtools/releases/tag/2021_06_29
> 试验一下这个能不能用

多谢，不折腾了，最终使用windows + wsl
