### ISSUE TITLE
什么时候能升级到 1.05呢

### ISSUE THREAD

**Issue by imic07** [dragonation/wechat-devtools#49]
现在是在manjaro kde下使用 1.03 ,目前发现复制代码准备粘贴的时候，先复制一段文本， 然后选中要被替换的文本，然后ctl + v， 就会发现粘贴上去的是要被替换的文本。 很不方便，希望修复下

**Comment by disburden** [comment]
这个好像是这个工具采用的框架自带的功能,会默认复制你选中的文件,配置文件中可以把这个功能关掉

**Comment by disburden** [comment]
不过我也期待升级到1.05

**Comment by imic07** [comment]
> 不过我也期待升级到1.05

就是没找到怎么配置.

**Comment by disburden** [comment]
文档里就有写:

FAQ
为什么在编辑器里编辑的文本会自动复制到剪贴板？

新版微信开发者工具使用了新的vseditor作为基础编辑器控件，而该控件在Linux下有一个默认配置支持Selection Clipboard。

// Controls whether the Linux primary clipboard should be supported.
"editor.selectionClipboard": true
如果不想用这个功能，可以自己通过修改~/.config/wechat_devtools/Default/Editor/User/settings.json文件关闭。也可以通过tools/fix-selection-copy命令来关闭该特性

**Comment by zhea55** [comment]
> 现在是在manjaro kde下使用 1.03 ,目前发现复制代码准备粘贴的时候，先复制一段文本， 然后选中要被替换的文本，然后ctl + v， 就会发现粘贴上去的是要被替换的文本。 很不方便，希望修复下

你们用了es6吗？

这个1.03我只能看到页面。

但是进行普通的登录操作，就有js报错，只能看看静态页面。

**Comment by imic07** [comment]
> > 现在是在manjaro kde下使用 1.03 ,目前发现复制代码准备粘贴的时候，先复制一段文本， 然后选中要被替换的文本，然后ctl + v， 就会发现粘贴上去的是要被替换的文本。 很不方便，希望修复下
> 
> 你们用了es6吗？
> 
> 这个1.03我只能看到页面。
> 
> 但是进行普通的登录操作，就有js报错，只能看看静态页面。

进入详情 》本地设置 》 把调试基础库设置到2.15.0 或者以下。js应该就正常了。

**Comment by imic07** [comment]
> 文档里就有写:
> 
> FAQ 为什么在编辑器里编辑的文本会自动复制到剪贴板？
> 
> 新版微信开发者工具使用了新的vseditor作为基础编辑器控件，而该控件在Linux下有一个默认配置支持Selection Clipboard。
> 
> // Controls whether the Linux primary clipboard should be supported. "editor.selectionClipboard": true 如果不想用这个功能，可以自己通过修改~/.config/wechat_devtools/Default/Editor/User/settings.json文件关闭。也可以通过tools/fix-selection-copy命令来关闭该特性

我是通过Manjaro的软件包管理器安装的。安装后是找不到这个位置的.

**Comment by zhea55** [comment]
> > 文档里就有写:
> > FAQ 为什么在编辑器里编辑的文本会自动复制到剪贴板？
> > 新版微信开发者工具使用了新的vseditor作为基础编辑器控件，而该控件在Linux下有一个默认配置支持Selection Clipboard。
> > // Controls whether the Linux primary clipboard should be supported. "editor.selectionClipboard": true 如果不想用这个功能，可以自己通过修改~/.config/wechat_devtools/Default/Editor/User/settings.json文件关闭。也可以通过tools/fix-selection-copy命令来关闭该特性
> 
> 我是通过Manjaro的软件包管理器安装的。安装后是找不到这个位置的.

恩，这个我弄好了。

我发现是uniapp没有使用package.json的问题。他的hbuilder工具用了另一份package.json

项目内的package.json，我把依赖全部升级，然后用命令行打出来的包，就和hbuilder打包出来的效果一样了。


我现在也是aur安装的1.03的版本，页面渲染正常，请求交互逻辑也正常。

控制台有一些乱七八糟的错误，不过不影响使用。


不知道什么时候可以升级1.05

**Comment by msojocs** [comment]
https://github.com/jiyeme/wechat-devtools
来了
![preview](https://github.com/jiyeme/wechat-devtools/raw/master/res/screenshots/1.05.2201240.png)

**Comment by zhea55** [comment]
> https://github.com/jiyeme/wechat-devtools 来了 ![preview](https://github.com/jiyeme/wechat-devtools/raw/master/res/screenshots/1.05.2201240.png)

还没有release。

必须要编译好的包。因为exe解压出来的node_modules，里面的包，编译起来缺少文件，报很多的错误。


另外希望能升级一下nwjs，我在manjaro上面测试过[0.46.0](https://nwjs.io/blog/v0.46.0)，这个版本是可用的。

再高的话，启动会提示找不到manifest文件。不清楚这个文件是做什么的。


还有nodejs，我也试过16.13.2LTS版本，也是可用的。

**Comment by msojocs** [comment]
> 
> 还没有release。
> 
> 必须要编译好的包。因为exe解压出来的node_modules，里面的包，编译起来缺少文件，报很多的错误。
> 
> 另外希望能升级一下nwjs，我在manjaro上面测试过[0.46.0](https://nwjs.io/blog/v0.46.0)，这个版本是可用的。
> 
> 再高的话，启动会提示找不到manifest文件。不清楚这个文件是做什么的。
> 
> 还有nodejs，我也试过16.13.2LTS版本，也是可用的。

脚本我用nodejs重写过了，修了一些小问题，也存在一些小问题（毕竟没有完全的测试）。
理想情况下，执行脚本能够实现`安装` `启用`一步到位。
我会尝试弄一个编译好的。

## nwjs的版本问题
目前我项目中用的是0.47.0，原因是0.47.1开始修复了一个"bug"，而没有这个"bug"会出现`nw is not defined`以及可能出现的其他错误
> Fix: Window opened with new_instance creates always mixed context (#7344)
> https://github.com/nwjs/nw.js/blob/nw60/CHANGELOG.md#0471--07-24-2020

0.49.2 开始增加了一个选项，可以恢复这个“bug”
> https://github.com/nwjs/nw.js/issues/7609  (无端猜测：根据这个反馈者的项目列表，可能是微信开发相关人员)
> https://github.com/nwjs/nw.js/blob/nw60/CHANGELOG.md#0492--11-01-2020

而微信开发者工具使用的是一个不存在的`0.49.3`版本，我猜测这个版本是默认将这个选项置为`true`
我会尝试相关操作看能不能升级版本。

**Comment by zhea55** [comment]
> > 还没有release。
> > 必须要编译好的包。因为exe解压出来的node_modules，里面的包，编译起来缺少文件，报很多的错误。
> > 另外希望能升级一下nwjs，我在manjaro上面测试过[0.46.0](https://nwjs.io/blog/v0.46.0)，这个版本是可用的。
> > 再高的话，启动会提示找不到manifest文件。不清楚这个文件是做什么的。
> > 还有nodejs，我也试过16.13.2LTS版本，也是可用的。
> 
> 脚本我用nodejs重写过了，修了一些小问题，也存在一些小问题（毕竟没有完全的测试）。 理想情况下，执行脚本能够实现`安装` `启用`一步到位。 我会尝试弄一个编译好的。
> ## nwjs的版本问题
> 
> 目前我项目中用的是0.47.0，原因是0.47.1开始修复了一个"bug"，而没有这个"bug"会出现`nw is not defined`以及可能出现的其他错误
> 
> > Fix: Window opened with new_instance creates always mixed context (#7344)
> > https://github.com/nwjs/nw.js/blob/nw60/CHANGELOG.md#0471--07-24-2020
> 
> 0.49.2 开始增加了一个选项，可以恢复这个“bug”
> 
> > [nwjs/nw.js#7609](https://github.com/nwjs/nw.js/issues/7609)  (无端猜测：根据这个反馈者的项目列表，可能是微信开发相关人员)
> > https://github.com/nwjs/nw.js/blob/nw60/CHANGELOG.md#0492--11-01-2020
> 
> 而微信开发者工具使用的是一个不存在的`0.49.3`版本，我猜测这个版本是默认将这个选项置为`true` 我会尝试相关操作看能不能升级版本。


我之前是使用[aur仓库的包](https://aur.archlinux.org/packages/wechat-devtools/)，
自己修改了nw和node的版本，然后进行编译，编译的过程中有很多问题。然后一个个的解决。

不知道为什么它这个版本刚刚好，手动升级微信开发者工具的版本，会有很多模块编译失败。

通过PKGBUILD，我了解到他们使用的nwjs不是官网的nwjs版本，而是淘宝镜像的。

和nwjs官网相同版本号的包相比，md5是不一样的。

可能他们自己改过包。
